[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "es_data_load"
version = "1.0"
authors = [
    { name = "Sarvo Madhavan", email = "smadhavan@air.org" },
]
description = "Python package to load data into elastic search"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "elasticsearch",
    "tqdm",
    "pymysql>=1.0",
]
[tool.setuptools.package-data]
"es_data_load.pv.schemas" = ["*.json"]
"es_data_load.pv.mappings.production" = ["*.json"]

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''