name: documentation
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements/docs.txt
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
